# Generated by Django 5.1.15 on 2026-05-16 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo_prisma', models.CharField(max_length=80, unique=True)),
                ('nome_site', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=2)),
                ('regional', models.CharField(max_length=120)),
                ('tipo_imovel', models.CharField(blank=True, max_length=80)),
                ('lider_coordenacao', models.CharField(blank=True, max_length=120)),
                ('tipo_site_sla', models.CharField(blank=True, max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['regional', 'cidade', 'nome_site'],
                'indexes': [models.Index(fields=['ativo_prisma'], name='chamados_at_ativo_p_d2fb72_idx'), models.Index(fields=['cidade'], name='chamados_at_cidade_853c94_idx'), models.Index(fields=['regional'], name='chamados_at_regiona_0f2dfc_idx'), models.Index(fields=['nome_site'], name='chamados_at_nome_si_83f2fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=80, unique=True)),
                ('data_abertura', models.DateTimeField()),
                ('solicitante', models.CharField(blank=True, max_length=120)),
                ('contato_solicitante', models.CharField(blank=True, max_length=80)),
                ('dados_portaria_retirada_chave', models.TextField(blank=True)),
                ('denominacao', models.CharField(blank=True, max_length=120)),
                ('acao_tomada', models.CharField(blank=True, max_length=160)),
                ('command_center', models.CharField(blank=True, max_length=120)),
                ('detalhamento_situacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('nao_emergencial', 'Não emergencial')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='chamados.ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='chamados.fornecedor')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_abertura', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('abertura_emergencial', 'Abertura emergencial'), ('atualizacao_status', 'Atualização de status'), ('comentario', 'Comentário')], default='comentario', max_length=30)),
                ('texto_atualizacao', models.TextField()),
                ('status_resultante', models.CharField(choices=[('aberto', 'Aberto'), ('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('nao_emergencial', 'Não emergencial')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizacoes_chamados', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Atualização de chamado',
                'verbose_name_plural': 'Atualizações de chamados',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['chamado'], name='chamados_at_chamado_e32d2d_idx'), models.Index(fields=['tipo_evento'], name='chamados_at_tipo_ev_945d0c_idx'), models.Index(fields=['status_resultante'], name='chamados_at_status__6e0639_idx'), models.Index(fields=['criado_em'], name='chamados_at_criado__02024e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['numero_os'], name='chamados_ch_numero__c05208_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['data_abertura'], name='chamados_ch_data_ab_c4c1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['status'], name='chamados_ch_status_f7e4eb_idx'),
        ),
    ]
