# Generated by Django 5.1.15 on 2026-05-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='empresa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estados_atendidos',
            field=models.CharField(blank=True, help_text='UFs separadas por vírgula, ex.: SP, RJ, MG', max_length=255),
        ),
    ]
