# Generated by Django 5.1.15 on 2026-05-16 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_fornecedor_empresa_fornecedor_estados_atendidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='O que está sendo feito na obra.')),
                ('data_inicio', models.DateField()),
                ('data_fim_planejada', models.DateField()),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='chamados.ativo')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-data_inicio', 'ativo__nome_site'],
                'indexes': [models.Index(fields=['ativo'], name='chamados_ob_ativo_i_87730d_idx'), models.Index(fields=['data_inicio'], name='chamados_ob_data_in_596578_idx'), models.Index(fields=['data_fim_planejada'], name='chamados_ob_data_fi_224311_idx'), models.Index(fields=['ativa'], name='chamados_ob_ativa_b06128_idx')],
            },
        ),
    ]
