# Generated by Django 5.1.15 on 2026-05-23 17:35

import chamados.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_seed_fornecedores_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=chamados.models.evidencia_upload_to)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo'), ('pdf', 'PDF'), ('outro', 'Outro')], default='imagem', max_length=10)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='chamados.atualizacaochamado')),
            ],
            options={
                'verbose_name': 'Evidência',
                'verbose_name_plural': 'Evidências',
                'ordering': ['ordem', 'criado_em'],
                'indexes': [models.Index(fields=['atualizacao'], name='chamados_ev_atualiz_5f563a_idx'), models.Index(fields=['tipo'], name='chamados_ev_tipo_f6aeda_idx')],
            },
        ),
    ]
