# Generated by Django 5.1.15 on 2026-05-23 20:17

import chamados.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaochamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atualizacoes', to='chamados.chamado'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='arquivo',
            field=models.FileField(upload_to=chamados.models.evidencia_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'mp4', 'mov', 'avi', 'mkv', 'webm', 'pdf'])], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='atualizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='chamados.atualizacaochamado'),
        ),
    ]
