# Generated by Django 5.1.15 on 2026-05-23 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_alter_atualizacaochamado_chamado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['ativo'], name='chamados_at_ativo_5f7898_idx'),
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['uf'], name='chamados_at_uf_e7126c_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['data_abertura', 'criado_em'], name='chamado_data_criado_idx'),
        ),
    ]
